Web.App/Controllers/PerumahanController.cs
using App.Applications.DtoCollection.Perumahan;
using App.Applications.DtoCollection.Perumahan.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Web.App.Controllers
{
    [Authorize]
    public class PerumahanController : Controller
    {
        private readonly IPerumahanServices _service;

        public PerumahanController(IPerumahanServices _service)
        {
            this._service = _service;
        }
        // GET: Perumahan
        public ActionResult Index()
        {
            ViewBag.JenisRUmah = Enum.GetValues(typeof(TypeRumah));
            return View(_service.GetList().listObj);
        }

        public ActionResult Load()
        {
            //jQuery DataTables Param
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            //Find paging info
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();

            //find search columns info
            var typeRumah = Request.Form.GetValues("columns[0][search][value]").FirstOrDefault();
            var search = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();

            var get = _service.GetListPageDataTable(new GetDataTable
            {
                draw = draw,
                start = start,
                length = length,
                typeRumah = !string.IsNullOrEmpty(typeRumah) ? Convert.ToInt16(typeRumah) : default(int?),
                search = search,
            });

            return Json(new
            {
                draw = get.draw,
                recordsFiltered = get.recordsFiltered,
                recordsTotal = get.recordsTotal,
                data = get.data,
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LoadMap(int? type,string search)
        {
            var query = _service.GetQuery();
            if (type.HasValue)
            {
                query = query.Where(p=>p.typeRumah==type.Value);
            }
            if (!string.IsNullOrEmpty(search))
            {
                query = query.Where(p => p.alamatRumah.Contains(search.ToLower()));
            }

            var data = query.ToList();
            return Json(new
            {
                dataMap = data
            }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CariRute(List<int> Id)
        {
            var data = new List<PerumahanViewModel>();
            if (Id.Count > 0)
            {
                foreach (var item in Id)
                {
                    var single = _service.GetDetails(item);
                    if (single!=null)
                    {
                        data.Add(single.obj);
                    }
                }
            }
            return View(data);
        }

        public ActionResult LoadRute(string lat,string lon)
        {
            return Json(new { });
        }

        // GET: Perumahan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var perum = _service.GetDetails(id.Value);
            if (perum.obj == null)
            {
                return HttpNotFound();
            }
            return View(perum.obj);
        }

        // GET: Perumahan/Create
        public ActionResult Create()
        {
            ViewBag.JenisRUmah = Enum.GetValues(typeof(TypeRumah));
            return View();
        }

        // POST: Perumahan/Create
        [HttpPost]
        public ActionResult Create(PerumahanViewModel model)
        {
            if (ModelState.IsValid)
            {
                var add = _service.Create(model);
                if (add.status.Succeeded)
                {
                    TempData["code"] = "200";
                    TempData["msg"] = "Data Berhasil Di simpan";
                }
                else
                {
                    TempData["code"] = "500";
                    TempData["msg"] = add.status.description;
                }
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Perumahan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var get = _service.GetDetails(id.Value);
            if (!get.status.Succeeded)
            {
                return HttpNotFound();
            }
            ViewBag.JenisRUmah = Enum.GetValues(typeof(TypeRumah));
            return View(get.obj);
        }

        // POST: Perumahan/Edit/5
        [HttpPost]
        public ActionResult Edit(PerumahanViewModel model)
        {
            if (ModelState.IsValid)
            {
                var add = _service.Update(model);
                if (add.status.Succeeded)
                {
                    TempData["code"] = "200";
                    TempData["msg"] = "Data Berhasil Di Ubah";
                }
                else
                {
                    TempData["code"] = "500";
                    TempData["msg"] = add.status.description;
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //// GET: Perumahan/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    var get = _service.GetDetails(id.Value);
        //    if (!get.status.Succeeded)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(get.obj);
        //}

        // POST: Perumahan/Delete/5
        public ActionResult Delete(int id)
        {
            var add = _service.Delete(id);
            if (add.status.Succeeded)
            {
                TempData["code"] = "200";
                TempData["msg"] = "Data Berhasil Di Hapus";
            }
            else
            {
                TempData["code"] = "500";
                TempData["msg"] = add.status.description;
            }
            return RedirectToAction("Index");
        }
    }
}

Web.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Ela Admin - HTML5 Admin Template</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="~/Content/BackEndAsset/images/favicon.png">
    <link rel="shortcut icon" href="~/Content/BackEndAsset/images/favicon.png">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/css/normalize.css">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/css/themify-icons.css">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/css/pe-icon-7-filled.css">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/css/lib/datatable/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/js/lib/sweetalert2/sweetalert2.min.css">
    <link rel="stylesheet" href="~/Content/BackEndAsset/assets/css/style.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
</head>
<body class="bg-dark">

    <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="@Url.Action("Index","Home")"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                    </li>
                    <li class="menu-title">Perumahan</li><!-- /.menu-title -->
                    <li class="">
                        <a href="@Url.Action("Index","Perumahan")"><i class="menu-icon fa fa-laptop"></i>Perumahan </a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside><!-- /#left-panel -->
    <!-- Left Panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">

        <!-- Header-->
        <header id="header" class="header">
            <div class="top-left">
                <div class="navbar-header">
                    <a class="navbar-brand" href="./"><img src="images/logo.png" alt="Logo"></a>
                    <a class="navbar-brand hidden" href="./"><img src="images/logo2.png" alt="Logo"></a>
                    <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
                </div>
            </div>
            <div class="top-right">
                <div class="header-menu">
                    <div class="header-left">
                    </div>
                    @Html.Partial("_LoginPartial")

                </div>
            </div>
        </header><!-- /header -->
        <!-- Header-->


        <div class="content pb-0" style="min-height:500px">
            <div class="animated fadeIn">
                @RenderBody()
            </div>
        </div> <!-- .content -->

        <div class="clearfix"></div>

        <footer class="site-footer">
            <div class="footer-inner bg-white">
                <div class="row">
                    <div class="col-sm-6">
                        Copyright &copy; 2018 Ela Admin
                    </div>
                    <div class="col-sm-6 text-right">
                        Designed by <a href="https://colorlib.com">Colorlib</a>
                    </div>
                </div>
            </div>
        </footer>

    </div><!-- /#right-panel -->
    <script src="~/Content/BackEndAsset/assets/js/vendor/jquery-2.1.4.min.js"></script>
    <script src="~/Content/BackEndAsset/assets/js/popper.min.js"></script>
    <script src="~/Content/BackEndAsset/assets/js/plugins.js"></script>
    <script src="~/Content/BackEndAsset/assets/js/main.js"></script>

    <script src="~/Content/BackEndAsset/assets/js/lib/data-table/datatables.min.js"></script>
    <script src="~/Content/BackEndAsset/assets/js/lib/data-table/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/BackEndAsset/assets/js/lib/sweetalert2/sweetalert2.min.js"></script>
    @*<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&key=AIzaSyB-A7fRb75bS5cVT3bvksm-kazLj2hViOc&callback=initMap"></script>*@
    @*<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCNppW2L1rUCFA4JGZZnAlYW1imPW3ZPgA" type="text/javascript"></script>*@
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyB-A7fRb75bS5cVT3bvksm-kazLj2hViOc" type="text/javascript"></script>
    <script type="text/javascript" src="~/Content/BackEndAsset/assets/js/lib/gmap/jquery-gmaps-latlon-picker.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/BackEndAsset/assets/js/lib/fileinput/Fileinput.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/BackEndAsset/assets/js/lib/gmap/jquery-gmaps-latlon-picker.css" />
    <script src="~/Content/BackEndAsset/assets/js/lib/fileinput/fileinput.min.js"></script>

    <link rel="stylesheet" type="text/css" href="~/Content/BackEndAsset/assets/js/lib/data-table/DataTables.plugins.checkboxes.css" />
    <script src="~/Content/BackEndAsset/assets/js/lib/data-table/DataTables.plugins.checkboxes.js"></script>

    <script>
        var getUrl = window.location;
        var baseUrl = getUrl.protocol + "//" + getUrl.host + "/";
        jQuery(function ($) {
            $('.dataTable').DataTable();
              //allert staus
            var ststus = "@TempData["code"]";
            if (ststus == "200") {
                swal("Success!", "@TempData["msg"]", "success")
            } else if (ststus == "500") {
                swal("Opss!", "@TempData["msg"]", "error")
             }
        });

        function ON_Delete(Dom) {
            swal({
                title: 'Anda Yakin?',
                text: 'Untuk menghapus data ini ?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Ya, Lakukan!',
                cancelButtonText: 'Tidak',
            }).then((result) => {
                if (result.value) {
                    window.open(baseUrl + Dom.id, "_self")
                }

            })
        }
    </script>
    @RenderSection("Scripts", required: false)

</body>
</html>